services:
  - type: web
    name: employee-attendance-portal
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app:create_app()" --workers 2 --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DB_TYPE
        value: sqlite
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
